language: node_js
node_js:
- '6'
- '8'
- '10'
script:
- "npm install"
- "curl $GP_FAKE_BROKER > local-credentials.json"
- if [[ $TRAVIS_NODE_VERSION == '8' ]];
  then nyc npm test && nyc report --reporter=text-lcov | coveralls;
  else npm test;
  fi
env:
  global:
    # fakebroker
    - secure: "ddHbHMp/jzKzj5x5nSYoc3A9P0fmeCpMFXoziicfP4K/VwkOw+nUln17+heEHM1Q3Flk5+2UWWmiD76fNgkYCFtLMtnD4Soxy8WHnL5xIEtUVeauHhn4nIJWZ7YqMfCDXfImvygE/HEDfjDMTLJm3r0IzCbGubRlHlnUp6oHZ8o="

cache:
  directories:
    - node_modules # NPM packages
    - .nvm # why not

